name: Build

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world!"
        shell: bash
#  pipeline:
#    uses: yonatankarp/github-actions/.github/workflows/ci.yml@v1
#    with:
#      app_name: fetcher
#      build_dockerfile: false # Temp disable build until dockerfile will be set

#  dependabot_auto_merge:
#    needs: pipeline
#    if: ${{ github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]' }}
#    uses: yonatankarp/github-actions/.github/workflows/dependabot-auto-merge.yml@v1
#    secrets:
#      GITHUB_PAT: ${{ secrets.PAT }}
#
#  linters:
#    uses: yonatankarp/github-actions/.github/workflows/linters.yml@v1
