name: Generate PUML Diagram

on:
  pull_request:
    paths:
      - 'docs/c4/**.puml'
  workflow_dispatch:

jobs:
  generate-diagram:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Diagram PNG
        uses: Timmy/plantuml-action@v1
        with:
          args: './docs/c4/architecture.puml'

      - name: Commit Diagram to Branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git diff-index --quiet HEAD || git commit -m 'Update architecture diagram'
          git push origin HEAD:${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
